package main

import (
	"context"
	"log"
	"net/http"

	_ "rules-resolution-service/docs" // generated by swag
	"rules-resolution-service/internal/config"
	dbOps "rules-resolution-service/internal/db"
	"rules-resolution-service/internal/handler"
	"rules-resolution-service/internal/middleware"
	"rules-resolution-service/internal/repository"
	"rules-resolution-service/internal/service"
	db "rules-resolution-service/pkg/db"

	"github.com/go-chi/chi/v5"
	httpSwagger "github.com/swaggo/http-swagger"
)

// @title Rules Resolution Service API
// @version 1.0
// @description API for resolving rule overrides
// @host localhost:8080
// @BasePath /
func main() {
    cfg := config.Load()
    conn := db.Connect(cfg.DBUrl)
    dbOps.RunMigrations(cfg.DBUrl)
    dbOps.SeedSteps(context.Background(), conn)
    dbOps.SeedDefaults(context.Background(), conn)

    repo := repository.NewPostgresOverrideRepository(conn)
    dbOps.SeedOverrides(context.Background(), repo)
    resolver := service.NewResolver(repo)
    overrideService := service.NewOverrideService(repo)

    resolveHandler := handler.NewResolveHandler(resolver)
    overrideHandler := handler.NewOverrideHandler(overrideService)
    explainHandler := handler.NewExplainHandler(resolver)
    conflictHandler := handler.NewConflictHandler(overrideService)
    healthHandler := handler.NewHealthHandler()

    r := chi.NewRouter()
    r.Use(middleware.Logging)
    // Swagger route
    r.Get("/swagger/*", httpSwagger.Handler(
        httpSwagger.URL("/swagger/doc.json"), // The url pointing to your swagger.json
    ))
 r.Route("/api", func(r chi.Router) {
    r.Get("/overrides/conflicts", conflictHandler.GetConflicts)
    r.Get("/overrides", overrideHandler.List)
    r.Get("/overrides/{id}", overrideHandler.GetByID)
    r.Post("/overrides", overrideHandler.Create)
    r.Put("/overrides/{id}", overrideHandler.Update)
    r.Patch("/overrides/{id}/status", overrideHandler.UpdateStatus)
    r.Post("/resolve", resolveHandler.Resolve)
    r.Post("/bulk-resolve", resolveHandler.BulkResolve)
    r.Post("/resolve/explain", explainHandler.Explain)
    r.Get("/health", healthHandler.Health)
})

    log.Println("Server running on :8080")
    http.ListenAndServe(":8080", r)
}